[phases.setup]
nixPkgs = ["bun"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build"]

[phases.start]
dependsOn = ["build"]
cmds = ["bun run preview"]
